create database vet_clinic;

CREATE TABLE animals (
	id INT GENERATED By Default AS IDENTITY,
	name VARCHAR(25),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BOOLEAN,
	weight_kg DECIMAL,
	PRIMARY KEY(id)
);

ALTER TABLE animals
ADD species VARCHAR(25); 